---
title: "GGBN Sample Query"
author: "Michael JV O'Mahoney"
date: "March 2021"
output: html_notebook
---

## Loading Libraries
```{r}
# needed to run fromJSON(), 
library('jsonlite')
# needed to run rbind.fill()
library('plyr')
# needed to run the progress_bar
library('progress')
# needed to run flatten()
library('purrr')
# needed to run RCurl()
library('RCurl')
# needed to run str_replace_all()
library('stringr')
# needed to run write_tsv()
library('readr')
```


## Initialize the Function
```{r}
GGBN_sample_query <- function(data_file = NULL, head = NULL, column = NULL) {
  # Validation check for NULL values function arguments 
  if (is.null(data_file) & is.null(head) & is.null(column)) {
    print("You didn't enter any arguments... Are you even trying to use this function?")
  } else if (is.null(data_file) & is.null(head)) {
    print("data_file argument and head argument are both NULL Enter the correct values for both to proceed with function")
  } else if (is.null(data_file) & is.null(column)) {
    print("data_file argument and column argument are both NULL Enter the correct values for both to proceed with function")
  } else if (is.null(head) & is.null(column)) {
    print("head argument and column argument are both NULL Enter the correct values for both to proceed with function")
  } else if (is.null(data_file)) {
    print("data_file argument is NULL Please supply appropriate data file")
  } else if (is.null(head)) {
    print("head argument is NULL Please indicate the presence of table header with TRUE or FALSE")
  } else if (is.null(column)) {
    print("column argument is NULL Please indicate the header name or numeric column position of the taxonomic names to be queried")
  } else {
    # Validation check on file type for data_file argument and Boolean entry for
    # head argument. If pass the file is loaded as a data frame
    if (!is.logical(head)) {
      print("head argument was provided in incorrect format. Please enter either TRUE or FALSE")
    } else if (grepl("^.*\\.csv", data_file)) {
      data <- read.table(file = data_file, header = head, sep = ",")
    } else if (grepl("^.*\\.tsv|^.*\\.txt", data_file)) {
      data <- read.table(file = data_file, header = head, sep = "\t")
    } else {
      print("Incorrect data format. Please load .csv, .tsv, or .txt file")
    }
    
    # Validation check that column value can be found in header values if it is
    # a string or if it is a numeric value instead. If pass the taxa column is 
    # extracted, white space is trimmed, and stored as taxa_list vector
    if (column %in% names(data) || is.numeric(column)) {
      taxa_list <- 
        data[[column]] %>%
        trimws()
      
      # Create new instance of the progress bar with ETA
      pb <- progress_bar$new(
        format = "  downloading [:bar] :percent eta: :eta",
        total = length(taxa_list), clear = FALSE, width= 60)
      
      # The base URL used to query the API
      base <- "http://data.ggbn.org/ggbn_portal/api/search?getSampletype&name="
      
      # function that queries GGBN for available sample type data
      GGBN_query <- function(taxa) {
        # Initiate progress bar with ETA
        pb$tick(0)
        # Update progress bar each time the function is run
        pb$tick()
        
        # Query GGBN API and store flattened JSON response in request
        request <- 
          base %>%
          paste0(taxa) %>%
          URLencode() %>%
          getURL() %>%
          fromJSON() %>%
          flatten() %>%
          as.data.frame()
      }
      
      # Run sapply() to query each species in the taxa list using GGBN_query()
      df <- 
        taxa_list %>%
        sapply(FUN = GGBN_query)
      
      # Convert df from a list of lists to a data.frame
      df <- do.call(rbind.fill, df)
      
      # Remove "fullScientificName_nc=" from the species query
      df$filters <- str_replace_all(df$filters, "^.*=", "")
      
      return(df)
      
    } else if (head == FALSE && is.character(column) == TRUE) {
      print("You entered FALSE for the head argument and a string for the column argument. Please check your file again and re-enter a vaild combination")
    } else {
      print("Please enter TRUE or FALSE for the head argument and check the spelling of the column argument")
    }
    
  }
}
```


## Execute the Function
* `data_file`: Enter the file containg the taxonomy
* `head`: Indicate weather the `data_file` has a header using `TRUE` or `FALSE`
* `column`: Enter either the header string or the numeric value of the column you want to query
```{r}
df <- GGBN_sample_query(data_file = '', 
                        head = , column = )
```


## Save the output to TSV
```{r}
write_tsv(df, 'GGBN_Query_results.tsv', na = "NA")
```

